USE EDU_MANAGEMENT

-- 3. Tìm tất cả mã học viên, tên học viên có đăng ký môn học

SELECT
*
FROM ENROLLMENTS

-- CÁCH 1----
SELECT
    DISTINCT [sID]
FROM ENROLLMENTS

SELECT DISTINCT [sID], [sFirstName]
FROM STUDENTS
WHERE [sID] IN ('M0001','M0002','M0003','M0004','M0005','M0006')

-- CÁCH 2 --
SELECT
    DISTINCT [sID]
FROM ENROLLMENTS

SELECT DISTINCT [sID], [sFirstName]
FROM STUDENTS
WHERE [sID] IN 
(
    SELECT
    DISTINCT [sID]
    FROM ENROLLMENTS
)

-- CÁCH 3 DÙNG JOIN --
SELECT 
    DISTINCT STUDENTS.[sID], STUDENTS.[sFirstName]
FROM STUDENTS JOIN ENROLLMENTS 
ON STUDENTS.sID=ENROLLMENTS.sID 

SELECT * FROM
STUDENTS JOIN ENROLLMENTS 
ON STUDENTS.sID=ENROLLMENTS.sID 


-- 4. Tìm tất cả mã học viên, tên học viên KHÔNG có đăng ký môn học

SELECT * FROM ENROLLMENTS

-- CÁCH 1----
SELECT
    DISTINCT [sID]
FROM ENROLLMENTS

SELECT DISTINCT [sID], [sFirstName]
FROM STUDENTS
WHERE [sID] NOT IN ('M0001','M0002','M0003','M0004','M0005','M0006')

-- CÁCH 2 --
SELECT
    DISTINCT [sID]
FROM ENROLLMENTS

SELECT DISTINCT [sID], [sFirstName]
FROM STUDENTS
WHERE [sID] NOT IN 
(
    SELECT
    DISTINCT [sID]
    FROM ENROLLMENTS
)


-- CÁCH 3 DÙNG JOIN --

SELECT * FROM
STUDENTS LEFT JOIN  ENROLLMENTS 
ON STUDENTS.sID=ENROLLMENTS.sID 
WHERE ENROLLMENTS.sID is NULL